-- GENERATED by scripts/schema-dev.ts from schema.sql — do not edit by hand.
-- Development copy of the schema: tables in the "dev" namespace, files in the "photos-dev" bucket.
create schema if not exists dev;
grant usage on schema dev to anon, authenticated, service_role;
alter default privileges in schema dev grant all on tables to anon, authenticated, service_role;
alter default privileges in schema dev grant all on functions to anon, authenticated, service_role;
alter default privileges in schema dev grant all on sequences to anon, authenticated, service_role;

-- ============================================================================
-- Wedding photo wall — Supabase schema
-- Paste this whole file into: Supabase Dashboard → SQL Editor → New query → Run
-- Safe to re-run.
-- ============================================================================

create extension if not exists pgcrypto;

-- ── Tables ──────────────────────────────────────────────────────────────────
create table if not exists dev.guests (
  id          uuid primary key default gen_random_uuid(),
  auth_id     uuid not null unique references auth.users(id) on delete cascade,
  name        text not null check (char_length(btrim(name)) between 1 and 40),
  avatar_path text,
  created_at  timestamptz not null default now()
);

create table if not exists dev.photos (
  id          uuid primary key default gen_random_uuid(),
  guest_id    uuid not null references dev.guests(id) on delete cascade,
  path        text not null,
  thumb_path  text not null,
  width       int,
  height      int,
  caption     text check (caption is null or char_length(caption) <= 200),
  created_at  timestamptz not null default now()
);
create index if not exists photos_created_at_idx on dev.photos (created_at desc);

-- v2.1: optional social links shown on the guest card ({ "instagram": "…", "x": "…", "tiktok": "…", "website": "…" })
alter table dev.guests add column if not exists socials jsonb not null default '{}'::jsonb;

-- v1.2: videos. (alter … if not exists so re-running on an older database upgrades it)
alter table dev.photos add column if not exists kind text not null default 'photo' check (kind in ('photo', 'video'));
alter table dev.photos add column if not exists duration real;

create table if not exists dev.hearts (
  photo_id    uuid not null references dev.photos(id) on delete cascade,
  guest_id    uuid not null references dev.guests(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (photo_id, guest_id)
);

-- Written only by scripts/rank.ts (service role). Guests can read.
create table if not exists dev.photo_scores (
  photo_id    uuid primary key references dev.photos(id) on delete cascade,
  score       numeric(4,2) not null check (score between 0 and 10),
  theme       text not null,
  tags        text[] not null default '{}',
  reason      text,
  model       text,
  scored_at   timestamptz not null default now()
);

-- ── Helper ──────────────────────────────────────────────────────────────────
create or replace function dev.current_guest_id()
returns uuid language sql stable security definer set search_path = dev as $$
  select id from dev.guests where auth_id = auth.uid()
$$;

-- ── Row-level security ──────────────────────────────────────────────────────
alter table dev.guests       enable row level security;
alter table dev.photos       enable row level security;
alter table dev.hearts       enable row level security;
alter table dev.photo_scores enable row level security;

drop policy if exists "guests: read all"        on dev.guests;
drop policy if exists "guests: insert self"     on dev.guests;
drop policy if exists "guests: update self"     on dev.guests;
drop policy if exists "photos: read all"        on dev.photos;
drop policy if exists "photos: insert own"      on dev.photos;
drop policy if exists "photos: delete own"      on dev.photos;
drop policy if exists "hearts: read all"        on dev.hearts;
drop policy if exists "hearts: insert own"      on dev.hearts;
drop policy if exists "hearts: delete own"      on dev.hearts;
drop policy if exists "scores: read all"        on dev.photo_scores;

create policy "guests: read all"    on dev.guests for select to authenticated using (true);
create policy "guests: insert self" on dev.guests for insert to authenticated with check (auth_id = auth.uid());
create policy "guests: update self" on dev.guests for update to authenticated using (auth_id = auth.uid());

create policy "photos: read all"    on dev.photos for select to authenticated using (true);
create policy "photos: insert own"  on dev.photos for insert to authenticated with check (guest_id = dev.current_guest_id());
create policy "photos: delete own"  on dev.photos for delete to authenticated using (guest_id = dev.current_guest_id());

create policy "hearts: read all"    on dev.hearts for select to authenticated using (true);
create policy "hearts: insert own"  on dev.hearts for insert to authenticated with check (guest_id = dev.current_guest_id());
create policy "hearts: delete own"  on dev.hearts for delete to authenticated using (guest_id = dev.current_guest_id());

create policy "scores: read all"    on dev.photo_scores for select to authenticated using (true);
-- (no insert/update policy on photo_scores → only the service role can write)

-- ── Realtime ────────────────────────────────────────────────────────────────
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'dev' and tablename = 'photos-dev') then
    alter publication supabase_realtime add table dev.photos;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'dev' and tablename = 'hearts') then
    alter publication supabase_realtime add table dev.hearts;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'dev' and tablename = 'photo_scores') then
    alter publication supabase_realtime add table dev.photo_scores;
  end if;
end $$;

-- ── Storage ─────────────────────────────────────────────────────────────────
-- Public bucket: photos are served by unguessable UUID URLs (no listing).
-- 50 MB is the per-file cap on Supabase's free tier; raise it on Pro if you want longer videos.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('photos-dev', 'photos-dev', true, 52428800,
        array['image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/quicktime', 'video/webm', 'video/3gpp', 'video/x-m4v'])
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "photos-dev bucket: read"          on storage.objects;
drop policy if exists "photos-dev bucket: upload own"    on storage.objects;
drop policy if exists "photos-dev bucket: delete own"    on storage.objects;

create policy "photos-dev bucket: read" on storage.objects
  for select to public using (bucket_id = 'photos-dev');
-- Each guest may only write inside a folder named after their auth uid.
create policy "photos-dev bucket: upload own" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'photos-dev' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "photos-dev bucket: delete own" on storage.objects
  for delete to authenticated
  using (bucket_id = 'photos-dev' and (storage.foldername(name))[1] = auth.uid()::text);

-- ── v2.6: unique names + reconnect by name ──────────────────────────────────
-- Names are unique (case-insensitive). A guest on a new phone types their name on
-- "Déjà inscrit ?" and the profile is re-linked to that device — no code.
drop trigger if exists guests_secret on dev.guests;
drop function if exists dev.guest_secret_on_insert();
drop function if exists dev.my_recovery_code();
drop function if exists dev.claim_guest(text, text);
drop function if exists dev.gen_recovery_code();
drop table if exists dev.guest_secrets;

-- Rename duplicates that exist already (the first one keeps the name, later ones get " 2", " 3"…)
do $$
declare r record; n int; candidate text;
begin
  for r in
    select id, name from (
      select id, name, row_number() over (partition by lower(btrim(name)) order by created_at) as rn from dev.guests
    ) d where rn > 1 order by name
  loop
    n := 2;
    loop
      candidate := btrim(r.name) || ' ' || n;
      exit when not exists (select 1 from dev.guests where lower(btrim(name)) = lower(candidate));
      n := n + 1;
    end loop;
    update dev.guests set name = candidate where id = r.id;
  end loop;
end $$;

create unique index if not exists guests_name_unique on dev.guests (lower(btrim(name)));

create or replace function dev.claim_guest(p_name text) returns setof dev.guests
language plpgsql security definer set search_path = dev as $$
declare gid uuid;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if exists (select 1 from dev.guests where auth_id = auth.uid()) then raise exception 'already registered'; end if;
  select id into gid from dev.guests where lower(btrim(name)) = lower(btrim(p_name)) limit 1;
  if gid is null then raise exception 'no guest with this name'; end if;
  update dev.guests set auth_id = auth.uid() where id = gid;
  return query select * from dev.guests where id = gid;
end $$;
grant execute on function dev.claim_guest(text) to authenticated;

-- ── v2.7: one profile, many devices ─────────────────────────────────────────
-- Each device (anonymous auth user) is linked to a guest through guest_devices, so a
-- phone and a laptop can both stay signed in as the same person.
create table if not exists dev.guest_devices (
  auth_id    uuid primary key references auth.users(id) on delete cascade,
  guest_id   uuid not null references dev.guests(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table dev.guest_devices enable row level security;
drop policy if exists "devices: read own" on dev.guest_devices;
create policy "devices: read own" on dev.guest_devices for select to authenticated using (auth_id = auth.uid());

insert into dev.guest_devices (auth_id, guest_id)
select g.auth_id, g.id from dev.guests g
on conflict (auth_id) do nothing;

-- Who am I? (through the devices table)
create or replace function dev.current_guest_id()
returns uuid language sql stable security definer set search_path = dev as $$
  select guest_id from dev.guest_devices where auth_id = auth.uid()
$$;

create or replace function dev.my_guest() returns setof dev.guests
language sql stable security definer set search_path = dev as $$
  select g.* from dev.guests g join dev.guest_devices d on d.guest_id = g.id where d.auth_id = auth.uid()
$$;
grant execute on function dev.my_guest() to authenticated;

-- The device that creates a profile is linked to it automatically.
create or replace function dev.guest_device_on_insert() returns trigger
language plpgsql security definer set search_path = dev as $$
begin
  insert into dev.guest_devices (auth_id, guest_id) values (new.auth_id, new.id)
  on conflict (auth_id) do update set guest_id = excluded.guest_id;
  return new;
end $$;
drop trigger if exists guests_device on dev.guests;
create trigger guests_device after insert on dev.guests for each row execute function dev.guest_device_on_insert();

-- Guests can edit their profile from any linked device.
drop policy if exists "guests: update self" on dev.guests;
create policy "guests: update self" on dev.guests for update to authenticated using (id = dev.current_guest_id());

-- Reconnect = add this device to the profile with that name (other devices stay linked).
create or replace function dev.claim_guest(p_name text) returns setof dev.guests
language plpgsql security definer set search_path = dev as $$
declare gid uuid;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if exists (select 1 from dev.guest_devices where auth_id = auth.uid()) then raise exception 'already registered'; end if;
  select id into gid from dev.guests where lower(btrim(name)) = lower(btrim(p_name)) limit 1;
  if gid is null then raise exception 'no guest with this name'; end if;
  insert into dev.guest_devices (auth_id, guest_id) values (auth.uid(), gid);
  return query select * from dev.guests where id = gid;
end $$;
grant execute on function dev.claim_guest(text) to authenticated;

-- ── v2.8: livre d'or (messages to the couple) ────────────────────────────────
create table if not exists dev.messages (
  id         uuid primary key default gen_random_uuid(),
  guest_id   uuid not null references dev.guests(id) on delete cascade,
  text       text not null check (char_length(btrim(text)) between 1 and 280),
  created_at timestamptz not null default now()
);
create index if not exists messages_created_at_idx on dev.messages (created_at desc);

create table if not exists dev.message_hearts (
  message_id uuid not null references dev.messages(id) on delete cascade,
  guest_id   uuid not null references dev.guests(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, guest_id)
);

alter table dev.messages       enable row level security;
alter table dev.message_hearts enable row level security;
drop policy if exists "messages: read all"   on dev.messages;
drop policy if exists "messages: insert own" on dev.messages;
drop policy if exists "messages: delete own" on dev.messages;
drop policy if exists "mhearts: read all"    on dev.message_hearts;
drop policy if exists "mhearts: insert own"  on dev.message_hearts;
drop policy if exists "mhearts: delete own"  on dev.message_hearts;
create policy "messages: read all"   on dev.messages for select to authenticated using (true);
create policy "messages: insert own" on dev.messages for insert to authenticated with check (guest_id = dev.current_guest_id());
create policy "messages: delete own" on dev.messages for delete to authenticated using (guest_id = dev.current_guest_id());
create policy "mhearts: read all"    on dev.message_hearts for select to authenticated using (true);
create policy "mhearts: insert own"  on dev.message_hearts for insert to authenticated with check (guest_id = dev.current_guest_id());
create policy "mhearts: delete own"  on dev.message_hearts for delete to authenticated using (guest_id = dev.current_guest_id());

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'dev' and tablename = 'messages') then
    alter publication supabase_realtime add table dev.messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'dev' and tablename = 'message_hearts') then
    alter publication supabase_realtime add table dev.message_hearts;
  end if;
end $$;

-- ── Migrations without copy/paste ───────────────────────────────────────────
-- Lets `npm run migrate` apply this file with the service-role key (never exposed to guests).
create or replace function dev.exec_sql(sql text) returns void
language plpgsql security definer set search_path = dev as $$
begin
  execute sql;
end $$;
revoke all on function dev.exec_sql(text) from public, anon, authenticated;
grant execute on function dev.exec_sql(text) to service_role;

grant all on all tables in schema dev to anon, authenticated, service_role;
grant all on all functions in schema dev to anon, authenticated, service_role;
