/**
 * Builds supabase/schema.dev.sql: the same schema, but in a `dev` namespace with a
 * `photos-dev` bucket, so development never touches the production tables.
 *   npm run schema:dev            # writes the file (paste it in the SQL editor)
 * The dev schema must also be exposed once: Supabase → Settings → API → Exposed schemas → add "dev".
 */
import { readFileSync, writeFileSync } from "node:fs";

const src = readFileSync(new URL("../supabase/schema.sql", import.meta.url), "utf8");
let out = src
  .replace(/\bpublic\./g, "dev.")
  .replace(/schemaname = 'public'/g, "schemaname = 'dev'")
  .replace(/search_path = public/g, "search_path = dev")
  .replace(/'photos'/g, "'photos-dev'")
  .replace(/"photos bucket: ([^"]+)"/g, '"photos-dev bucket: $1"');

out = `-- GENERATED by scripts/schema-dev.ts from schema.sql — do not edit by hand.
-- Development copy of the schema: tables in the "dev" namespace, files in the "photos-dev" bucket.
create schema if not exists dev;
grant usage on schema dev to anon, authenticated, service_role;
alter default privileges in schema dev grant all on tables to anon, authenticated, service_role;
alter default privileges in schema dev grant all on functions to anon, authenticated, service_role;
alter default privileges in schema dev grant all on sequences to anon, authenticated, service_role;

${out}
grant all on all tables in schema dev to anon, authenticated, service_role;
grant all on all functions in schema dev to anon, authenticated, service_role;
`;
writeFileSync(new URL("../supabase/schema.dev.sql", import.meta.url), out);
console.log("wrote supabase/schema.dev.sql");
